# Generated by Django 3.0.5 on 2020-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.BigIntegerField()),
                ('password', models.CharField(default='123456', max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, upload_to='doctors')),
                ('Portfolio', models.CharField(max_length=300)),
            ],
        ),
    ]
