# Generated by Django 3.0.5 on 2020-04-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200424_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='phoneno',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='profile_pic',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='email',
        ),
        migrations.AddField(
            model_name='hospital',
            name='Services',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Speciality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Dosage',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Precautions',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='SideEffects',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
