# Generated by Django 3.0.5 on 2020-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200427_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Usage',
            field=models.CharField(max_length=1000),
        ),
    ]
