# Generated by Django 3.0.5 on 2020-04-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200427_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='storage',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Dosage',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Manufacturer',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Precautions',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Salts',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='SideEffects',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
