# Generated by Django 3.0.5 on 2020-04-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200427_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='storage',
            new_name='Storage',
        ),
    ]
