# Generated by Django 3.0.5 on 2020-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200427_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Achievements',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Interests',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Portfolio',
            field=models.CharField(max_length=5000),
        ),
    ]
