# Generated by Django 3.0.5 on 2020-04-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200427_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Interests',
            new_name='Speciality',
        ),
    ]
