# Generated by Django 3.0.5 on 2020-04-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200427_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Services',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Speciality',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
