# Generated by Django 3.0.3 on 2020-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_editprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
