# Generated by Django 3.0.3 on 2020-05-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200511_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editprofile',
        ),
    ]
