# Generated by Django 3.0.3 on 2020-05-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_editprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.BigIntegerField()),
                ('pincode', models.BigIntegerField()),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=3000)),
            ],
        ),
    ]
