# Generated by Django 3.0.3 on 2020-05-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_editprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofile',
            name='dob',
            field=models.DateField(),
        ),
    ]
