# Generated by Django 3.0.3 on 2020-05-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200511_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changepassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpw', models.CharField(max_length=100)),
                ('newpw', models.CharField(max_length=100)),
                ('repw', models.CharField(max_length=100)),
            ],
        ),
    ]
