# Generated by Django 3.0.3 on 2020-05-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_changepassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Changepassword',
            new_name='Changepass',
        ),
    ]
