# Generated by Django 3.0.3 on 2020-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20200511_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpsupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='changepass',
            old_name='newpw',
            new_name='newpass',
        ),
        migrations.RenameField(
            model_name='changepass',
            old_name='oldpw',
            new_name='oldpass',
        ),
        migrations.RenameField(
            model_name='changepass',
            old_name='repw',
            new_name='repass',
        ),
    ]
