# Generated by Django 3.0.3 on 2020-05-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Changepass',
        ),
        migrations.DeleteModel(
            name='Helpsupport',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
