# Generated by Django 3.0.3 on 2020-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20200511_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpass', models.CharField(max_length=100)),
                ('newpass', models.CharField(max_length=100)),
                ('repass', models.CharField(max_length=100)),
            ],
        ),
    ]
