# Generated by Django 3.0.3 on 2020-05-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='pw',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='us',
        ),
    ]
