# Generated by Django 3.0.3 on 2020-05-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20200512_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
