# Generated by Django 3.0.3 on 2020-05-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
