# Generated by Django 3.0.3 on 2020-05-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
