# Generated by Django 3.0.3 on 2020-05-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='setpw',
            new_name='password',
        ),
    ]
