# Generated by Django 3.0.3 on 2020-05-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20200513_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
