# Generated by Django 3.0.3 on 2020-05-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
