# Generated by Django 3.0.3 on 2020-05-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_drlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drlogin',
        ),
        migrations.DeleteModel(
            name='Editprofile',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
