# Generated by Django 3.0.3 on 2020-05-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20200514_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
