# Generated by Django 3.0.3 on 2020-05-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changepass',
            old_name='newpass',
            new_name='newpassword',
        ),
        migrations.RenameField(
            model_name='changepass',
            old_name='oldpass',
            new_name='oldpassword',
        ),
        migrations.RenameField(
            model_name='changepass',
            old_name='repass',
            new_name='repassword',
        ),
    ]
