# Generated by Django 3.0.3 on 2020-05-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_auto_20200515_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Changepass',
        ),
    ]
