# Generated by Django 3.0.3 on 2020-05-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_delete_changepass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
