# Generated by Django 3.0.3 on 2020-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('pincode', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
